### ISSUE TITLE
Overview 30% (9/10)

### ISSUE THREAD

**Issue by ruvazi** [kasperpagh/UfoBlogHandIn#2]
The introduction to the subject is nicely written and the narrative have a red tread through the whole blog. The headlines to each part makes it easy to follow and understand. The sources at the end of the blog is valid. However all the pictures in the blog should be clearly accompanied by a text explaining the picture. You get 9 out of 10, over all great work.

**Comment by AKraunsoe** [comment]
We have added text to every picture as per request.
