### ISSUE TITLE
Reliable data from credible sources 10% (8/10)

### ISSUE THREAD

**Issue by ruvazi** [kasperpagh/UfoBlogHandIn#3]
You provide a good list of credible sources, but could have had some better references in your blog to which information comes from which sources.

**Comment by kasperpagh** [comment]
We have resolved this critique, by ensuring that our links (foot notes) that go to external sources are much more visible. This makes it explicit that there is a source connected to the text you're reading. The reader can either click the link (and be taken to the external source), or navigate to the bottom of the page, where the footnotes can be found.
